"""
Suggest macro placement for a new design using the trained FloorplanGNN.

Run inside the ORFS Docker container (for graph extraction), then on host (for inference):

Step 1 — extract graph (inside Docker):
    openroad -python ml/floorplan/data_collection/extract_netlist_graph.py \
        --odb /work/results/<platform>/<design>/base/1_synth.odb \
        --out /work/ml/data/<design>_graph.npz

Step 2 — suggest placement (on host):
    python3 ml/floorplan/integration/suggest_floorplan.py \
        --graph ml/data/<design>_graph.npz \
        --checkpoint ml/floorplan/model/checkpoints/best.pt \
        --die-w 500 --die-h 500 \
        --out flow/designs/nangate45/<design>/suggested_macros.tcl

The output Tcl file uses place_inst commands and should be reviewed and
edited before being sourced in a floorplan Tcl script.
"""

import argparse
import os
import sys
import numpy as np
import torch

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "model"))
from gnn import FloorplanGNN


def suggest(graph_path: str, checkpoint: str, device: torch.device):
    g = np.load(graph_path, allow_pickle=True)
    node_feat = torch.tensor(g["node_features"], dtype=torch.float32).to(device)
    edge_index = torch.tensor(g["edge_index"], dtype=torch.long).to(device)
    node_names = g["node_names"]
    num_macros = int(g["num_macros"][0])

    if num_macros == 0:
        print("No macros found in the netlist graph. Nothing to suggest.")
        return [], []

    # macro_mask: is_macro column (index 1) > 0.5
    macro_mask = node_feat[:, 1] > 0.5
    batch = torch.zeros(node_feat.shape[0], dtype=torch.long).to(device)

    model = FloorplanGNN()
    model.load_state_dict(torch.load(checkpoint, map_location=device))
    model.to(device)
    model.eval()

    with torch.no_grad():
        coords = model(node_feat, edge_index, batch, macro_mask)

    coords_np = coords.cpu().numpy()
    macro_names = node_names[macro_mask.cpu().numpy()]
    return macro_names, coords_np


def write_tcl(macro_names, coords, die_w_um: float, die_h_um: float, out_path: str):
    """Write a Tcl script of place_inst commands for each suggested macro."""
    lines = [
        "# Auto-generated macro placement suggestions",
        "# Review and edit before sourcing in your floorplan Tcl script",
        "# Generated by ml/floorplan/integration/suggest_floorplan.py",
        "",
    ]
    for name, (x_norm, y_norm) in zip(macro_names, coords):
        x_um = x_norm * die_w_um
        y_um = y_norm * die_h_um
        lines.append(f"place_inst {name} {x_um:.3f} {y_um:.3f} R0")

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Saved Tcl suggestions -> {out_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Suggest macro placement using FloorplanGNN"
    )
    parser.add_argument("--graph", required=True, help="Path to *_graph.npz file")
    parser.add_argument("--checkpoint", required=True, help="Model checkpoint .pt file")
    parser.add_argument(
        "--die-w",
        type=float,
        default=1000.0,
        help="Die width in microns (default 1000)",
    )
    parser.add_argument(
        "--die-h",
        type=float,
        default=1000.0,
        help="Die height in microns (default 1000)",
    )
    parser.add_argument("--out", required=True, help="Output Tcl file path")
    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    macro_names, coords = suggest(args.graph, args.checkpoint, device)

    if len(macro_names) == 0:
        return

    print(
        f"\nSuggested placement for {len(macro_names)} macros (die: {args.die_w}x{args.die_h} um):"
    )
    for name, (x, y) in zip(macro_names, coords):
        print(f"  {name}: x={x*args.die_w:.1f} um, y={y*args.die_h:.1f} um")

    write_tcl(macro_names, coords, args.die_w, args.die_h, args.out)


if __name__ == "__main__":
    main()
